version: '2'
services:
  dynamodb:
    image: tutum/dynamodb:latest
    ports:
      - "8000:8000"
  rabbit:
    image: bitnami/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - "8883:8883"
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./integrations.yml:/usr/local/stubby.yml
