version: '2'
services:
  dynamodb:
    image: tutum/dynamodb:latest
    ports:
      - "8000:8000"
  rabbit:
    image: bitnami/rabbitmq:latest
    ports:
      - "15672:15672"
    volumes:
      - "./plugins:/etc/rabbitmq/plugins"
