package br.com.vr.domains.shared;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public abstract class AggregateRoot<String> {

    protected String id;

    @DynamoDBAttribute(attributeName = "createBy")
    @Setter
    private String createBy;

    @DynamoDBAttribute(attributeName = "alterBy")
    @Setter
    private String alterBy;

    @DynamoDBVersionAttribute(attributeName = "version")
    @Setter
    private Long version;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "dateCreation")
    @Setter
    private Date dateCreation;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = "dateUpdate")
    @Setter
    private Date dataUpdate;

    private List<Event> events = new ArrayList<>();

    protected void apply(Event event) {
        events.add(event);
    }

    protected AggregateRoot() {
    }

    protected AggregateRoot(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public Iterable<Event> getEvents() {
        return events;
    }

}