package br.com.vr.domains;

import br.com.vr.infra.converters.LocalDateTimeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.joda.time.DateTime;

@DynamoDBDocument
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Transaction {

    @DynamoDBHashKey(attributeName = "transactionId")
    @DynamoDBAutoGeneratedKey
    @Setter
    private String transactionId;

    @DynamoDBAttribute(attributeName = "value")
    @Setter
    private Double value;

    @DynamoDBAttribute(attributeName = "cnpj")
    @Setter
    private String cnpj;

    @DynamoDBAttribute(attributeName = "dateTransaction")
    @Setter
    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private DateTime dateTransaction;

    @DynamoDBAttribute(attributeName = "transactionType")
    @Setter
    private String transactionType;

}
